// Kid-friendly phrases for Emojiword (ages 6-9).
// Letters only. Spaces separate words. Keep punctuation simple.
// Edit, add, or remove freely.

const PHRASES = [
  // Short & silly
  "THE CAT IS FAT",
  "I LIKE PIZZA",
  "JUMP HIGH",
  "MY DOG CAN RUN",
  "FROGS GO HOP",
  "BIG BLUE SKY",
  "ICE CREAM IS YUMMY",
  "I LOVE TO READ",
  "BEDTIME IS FUN",
  "SCHOOL IS COOL",

  // Animals
  "TIGERS HAVE STRIPES",
  "PENGUINS LIVE IN ICE",
  "ELEPHANTS ARE HUGE",
  "MONKEYS LIKE BANANAS",
  "OWLS HOOT AT NIGHT",
  "BEES MAKE HONEY",
  "DOLPHINS ARE SMART",
  "TURTLES MOVE SLOW",
  "PUPPIES ARE CUTE",
  "KITTENS PURR",

  // Nature
  "THE SUN IS BRIGHT",
  "RAIN MAKES PUDDLES",
  "STARS SHINE AT NIGHT",
  "TREES GROW TALL",
  "FLOWERS SMELL NICE",
  "THE MOON GLOWS",
  "RAINBOWS ARE PRETTY",
  "SNOW IS COLD",
  "WIND BLOWS LEAVES",
  "OCEANS ARE DEEP",

  // Fun activities
  "LETS GO TO THE PARK",
  "READING IS MAGIC",
  "SOCCER IS FUN",
  "I CAN RIDE A BIKE",
  "PAINTING IS FUN",
  "DANCING MAKES ME HAPPY",
  "BUILDING WITH BLOCKS",
  "JUMPING ON A TRAMPOLINE",
  "SWIMMING IN THE POOL",
  "PLAYING HIDE AND SEEK",

  // Food
  "I LOVE CHOCOLATE",
  "APPLES ARE CRUNCHY",
  "PANCAKES ARE TASTY",
  "COOKIES ARE SWEET",
  "I WANT POPCORN",
  "GRAPES ARE JUICY",
  "CHEESE IS YELLOW",
  "STRAWBERRIES ARE RED",

  // Sayings & encouragement
  "YOU CAN DO IT",
  "BE KIND TO OTHERS",
  "DREAMS COME TRUE",
  "FRIENDS ARE THE BEST",
  "PRACTICE MAKES PERFECT",
  "NEVER GIVE UP",
  "SHARING IS CARING",
  "SMILE EVERY DAY",
  "LAUGHTER IS THE BEST",
  "TODAY IS A GREAT DAY",

  // Imagination
  "DRAGONS CAN FLY",
  "UNICORNS ARE PINK",
  "ROBOTS LOVE TO BEEP",
  "PIRATES LOOK FOR GOLD",
  "WIZARDS CAST SPELLS",
  "MERMAIDS LIVE UNDER WATER",
  "ALIENS LIKE PLANETS",
  "SUPERHEROES SAVE THE DAY"
];

// Expose for browser
if (typeof window !== "undefined") {
  window.PHRASES = PHRASES;
}
